# Data cleaning (Again)

This is the url 
https://dataverse.nl/api/access/datafile/354098

In [27]:
from urllib.request import urlretrieve
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels 

url = "https://dataverse.nl/api/access/datafile/354098"

urlretrieve(url, )

('/var/folders/33/xqtwrk8s3ws6yhnm9qx48q2m0000gn/T/tmpmrw1h109',
 <http.client.HTTPMessage at 0x1513b8610>)

In [34]:
# Import the entire PWT from manual download
pwt_csv = pd.read_csv('pwt1001.csv',index_col=0)
pwt_csv

,countrycode,country,currency_unit,year,rgdpe,rgdpo,pop,emp,avh,hc,...,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k
0,ABW,Aruba,Aruban Guilder,1950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,Aruban Guilder,1951,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,Aruban Guilder,1952,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,Aruban Guilder,1953,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,Aruban Guilder,1954,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12805,ZWE,Zimbabwe,US Dollar,2015,40141.617,39798.645,13.814629,6.393752,NaN,2.584653,...,0.140172,-0.287693,-0.051930,0.479228,0.651287,0.541446,0.616689,0.533235,0.425715,1.778124
12806,ZWE,Zimbabwe,US Dollar,2016,41875.203,40963.190,14.030331,6.504374,NaN,2.616257,...,0.131920,-0.251232,-0.016258,0.470640,0.651027,0.539631,0.619789,0.519718,0.419446,1.728804
12807,ZWE,Zimbabwe,US Dollar,2017,44672.176,44316.742,14.236595,6.611773,NaN,2.648248,...,0.126722,-0.202827,-0.039897,0.473560,0.639560,0.519956,0.619738,0.552042,0.418681,1.756007
12808,ZWE,Zimbabwe,US Dollar,2018,44325.110,43420.900,14.438802,6.714952,NaN,2.680630,...,0.144485,-0.263658,-0.020791,0.543757,0.655473,0.529867,0.641361,0.561526,0.426527,1.830089
12809,ZWE,Zimbabwe,US Dollar,2019,42296.062,40826.570,14.645468,6.831016,NaN,2.713408,...,0.213562,-0.270959,-0.089798,0.494755,0.652439,0.500927,0.487763,0.430082,0.419883,1.580885

In [35]:

# filter the df for the variables of interest
var_of_int = ["countrycode", "year", "rgdpna", "rnna", "emp", "hc", "labsh"]

# remove all variables without interest
pwt_csv = pwt_csv[var_of_int]

# rename variables to well-known economic variables
pwt_csv = pwt_csv.rename(columns = {'rgdpna':'Y', "rnna":"K", "emp": "L"})

In [39]:

# drop nan and reset index
pwt_csv.dropna(inplace=True)
pwt_csv.reset_index(inplace=True, drop=True) 

# Generate variables of interest
pwt_csv["cap_out"] = pwt_csv["K"] / pwt_csv["Y"] # capital output ratio
pwt_csv["HC"] = pwt_csv["hc"] * pwt_csv["L"] # aggregate human capital
pwt_csv["capsh"] = 1 - pwt_csv["labsh"] # capital share as reciproc of labsh

# log transform
pwt_csv["lnY"] = np.log(pwt_csv["Y"])
pwt_csv["lnK"] = np.log(pwt_csv["K"])
pwt_csv["ln_capsh"] = np.log(pwt_csv["capsh"])
pwt_csv["ln_labsh"] = np.log(pwt_csv["labsh"])
pwt_csv["ln_cap_out"] = np.log(pwt_csv["K"] / pwt_csv["Y"])
pwt_csv["ln_cap_out_neg"] = -np.log(pwt_csv["K"] / pwt_csv["Y"])

In [41]:
# Sort values by countrycode and year to make functions possible
pwt_csv.sort_values(by=["countrycode", "year"])

,countrycode,year,Y,K,L,hc,labsh,cap_out,HC,capsh,lnY,ln_capsh,ln_labsh,ln_cap_out,ln_cap_out_neg,lnK
0,AGO,1970,54237.055,257238.100,3.666207,1.015686,0.284385,4.742848,3.723715,0.715615,10.901120,-0.334613,-1.257427,1.556638,-1.556638,12.457757
1,AGO,1971,57491.277,274282.500,3.742484,1.018196,0.284385,4.770854,3.810581,0.715615,10.959389,-0.334613,-1.257427,1.562525,-1.562525,12.521914
2,AGO,1972,57606.260,290921.900,3.853271,1.020711,0.284385,5.050179,3.933078,0.715615,10.961387,-0.334613,-1.257427,1.619424,-1.619424,12.580810
3,AGO,1973,62272.367,309321.280,3.987807,1.023234,0.284385,4.967232,4.080459,0.715615,11.039273,-0.334613,-1.257427,1.602863,-1.602863,12.642136
4,AGO,1974,64202.810,328087.000,4.130696,1.025762,0.284385,5.110166,4.237112,0.715615,11.069802,-0.334613,-1.257427,1.631232,-1.631232,12.701034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6809,ZWE,2015,42008.200,53550.227,6.393752,2.584653,0.533381,1.274757,16.525630,0.466619,10.645620,-0.762242,-0.628519,0.242755,-0.242755,10.888375
6810,ZWE,2016,42325.727,55167.008,6.504374,2.616257,0.533381,1.303392,17.017116,0.466619,10.653150,-0.762242,-0.628519,0.264970,-0.264970,10.918120
6811,ZWE,2017,44316.742,56829.140,6.611773,2.648248,0.533381,1.282340,17.509615,0.466619,10.699118,-0.762242,-0.628519,0.248687,-0.248687,10.947805
6812,ZWE,2018,46457.098,58552.810,6.714952,2.680630,0.533381,1.260363,18.000300,0.466619,10.746285,-0.762242,-0.628519,0.231400,-0.231400,10.977684
6813,ZWE,2019,42694.070,59743.035,6.831016,2.713408,0.533381,1.399329,18.535331,0.466619,10.661815,-0.762242,-0.628519,0.335993,-0.335993,10.997808

## Cleaning data for missing values

In [ ]:
# How many countries are removed 
num_countries_before = len(pwt_csv['countrycode'].unique())
num_countries_after = len(balanced_data['countrycode'].unique())

# Define functions to calculate the number of countries in each group
def num_countries_in_group(group_name, country_list):
    return len(pwt_csv[pwt_csv['countrycode'].isin(country_list)]['countrycode'].unique())

def num_countries_in_group_after_filter(group_name, country_list):
    return len(balanced_data[balanced_data['countrycode'].isin(country_list)]['countrycode'].unique())

# Calculate the number of countries in each group before filtering
num_countries_in_groups_before = {
    "world": num_countries_in_group("world", pwt_csv['countrycode'].unique()),
    "oecd": num_countries_in_group("oecd", oecd_countries),
    "imf_advanced": num_countries_in_group("imf_advanced", imf_advanced_countries),
    "imf_emerging": num_countries_in_group("imf_emerging", imf_emerging_countries)
}

# Calculate the number of countries in each group after filtering
num_countries_in_groups_after = {
    "world": num_countries_in_group_after_filter("world", pwt_csv['countrycode'].unique()),
    "oecd": num_countries_in_group_after_filter("oecd", oecd_countries),
    "imf_advanced": num_countries_in_group_after_filter("imf_advanced", imf_advanced_countries),
    "imf_emerging": num_countries_in_group_after_filter("imf_emerging", imf_emerging_countries)
}

# Calculate the number of countries removed from each group
num_countries_removed_from_groups = {
    group: num_countries_in_groups_before[group] - num_countries_in_groups_after[group]
    for group in num_countries_in_groups_before
}

# Print the results
for group, num_removed in num_countries_removed_from_groups.items():
    print(f"Number of countries removed from {group} group: {num_removed}")

Number of countries removed from world group: 40
Number of countries removed from oecd group: 8
Number of countries removed from imf_advanced group: 8
Number of countries removed from imf_emerging group: 32

In [40]:

# List of the 4 groups of interest
# entire set
world_data = pwt_csv.copy()

# Country groups are saved within the py-file and distributed between three groups: OECD countries, IMF advanced countries and IMF emerging countries
import Countries as con

# Define new dataframes as the country groups in the py-file
oecd_data = pwt_csv[pwt_csv['countrycode'].isin(con.oecd_countries)]
imf_advanced_data = pwt_csv[pwt_csv['countrycode'].isin(con.imf_advanced_countries)]
imf_emerging_data = pwt_csv[pwt_csv['countrycode'].isin(con.imf_emerging_countries)]

In [46]:
pwt_csv['g_K'] = pwt_csv['K'].pct_change(periods=1)*100
pwt_csv['g_Y'] = pwt_csv['Y'].pct_change(periods=1)*100

,countrycode,year,Y,K,L,hc,labsh,cap_out,HC,capsh,lnY,ln_capsh,ln_labsh,ln_cap_out,ln_cap_out_neg,lnK,g_K,g_Y
0,AGO,1970,54237.055,257238.10,3.666207,1.015686,0.284385,4.742848,3.723715,0.715615,10.901120,-0.334613,-1.257427,1.556638,-1.556638,12.457757,NaN,NaN
1,AGO,1971,57491.277,274282.50,3.742484,1.018196,0.284385,4.770854,3.810581,0.715615,10.959389,-0.334613,-1.257427,1.562525,-1.562525,12.521914,6.625924,5.999998
2,AGO,1972,57606.260,290921.90,3.853271,1.020711,0.284385,5.050179,3.933078,0.715615,10.961387,-0.334613,-1.257427,1.619424,-1.619424,12.580810,6.066519,0.200001
3,AGO,1973,62272.367,309321.28,3.987807,1.023234,0.284385,4.967232,4.080459,0.715615,11.039273,-0.334613,-1.257427,1.602863,-1.602863,12.642136,6.324508,8.100000
4,AGO,1974,64202.810,328087.00,4.130696,1.025762,0.284385,5.110166,4.237112,0.715615,11.069802,-0.334613,-1.257427,1.631232,-1.631232,12.701034,6.066741,3.099999
5,AGO,1975,60992.670,344396.75,4.270974,1.028297,0.284385,5.646527,4.391829,0.715615,11.018509,-0.334613,-1.257427,1.731041,-1.731041,12.749550,4.971166,-4.999999
6,AGO,1976,57821.050,358760.84,4.405441,1.030838,0.284385,6.204675,4.541295,0.715615,10.965108,-0.334613,-1.257427,1.825303,-1.825303,12.790411,4.170797,-5.200002
7,AGO,1977,58283.617,373623.94,4.537667,1.033385,0.284385,6.410445,4.689157,0.715615,10.973076,-0.334613,-1.257427,1.857929,-1.857929,12.831005,4.142899,0.799998
8,AGO,1978,55194.586,386334.75,4.670081,1.035939,0.284385,6.999504,4.837917,0.715615,10.918620,-0.334613,-1.257427,1.945839,-1.945839,12.864460,3.402033,-5.299999
9,AGO,1979,55360.168,398617.16,4.807217,1.038498,0.284385,7.200433,4.992286,0.715615,10.921616,-0.334613,-1.257427,1.974141,-1.974141,12.895757,3.179214,0.299997
10,AGO,1980,56688.816,409543.47,4.952234,1.041064,0.284385,7.224414,5.155595,0.715615,10.945332,-0.334613,-1.257427,1.977466,-1.977466,12.922798,2.741054,2.400007
11,AGO,1981,54194.504,420717.30,5.103069,1.050381,0.284385,7.763099,5.360166,0.715615,10.900335,-0.334613,-1.257427,2.049382,-2.049382,12.949716,2.728362,-4.400007
12,AGO,1982,54194.504,435114.10,5.259891,1.059781,0.284385,8.028750,5.574330,0.715615,10.900335,-0.334613,-1.257427,2.083029,-2.083029,12.983364,3.421965,0.000000
13,AGO,1983,56470.676,445289.12,5.422164,1.069264,0.284385,7.885316,5.797727,0.715615,10.941477,-0.334613,-1.257427,2.065002,-2.065002,13.006479,2.338472,4.200005
14,AGO,1984,59858.920,456745.88,5.589115,1.078833,0.284385,7.630373,6.029722,0.715615,10.999746,-0.334613,-1.257427,2.032137,-2.032137,13.031882,2.572881,6.000006
15,AGO,1985,61953.980,462508.44,5.760098,1.088488,0.284385,7.465355,6.269795,0.715615,11.034147,-0.334613,-1.257427,2.010273,-2.010273,13.044420,1.261656,3.499996
16,AGO,1986,63921.742,465385.97,5.935183,1.098228,0.284385,7.280558,6.518185,0.715615,11.065415,-0.334613,-1.257427,1.985208,-1.985208,13.050622,0.622157,3.176167
17,AGO,1987,68396.500,470316.16,6.114353,1.108056,0.284385,6.876319,6.775047,0.715615,11.133077,-0.334613,-1.257427,1.928083,-1.928083,13.061160,1.059377,7.000369
18,AGO,1988,72208.160,471586.88,6.296732,1.117972,0.284385,6.530936,7.039571,0.715615,11.187308,-0.334613,-1.257427,1.876550,-1.876550,13.063859,0.270184,5.572888
19,AGO,1989,72487.945,470103.38,6.481249,1.127977,0.284385,6.485263,7.310699,0.715615,11.191176,-0.334613,-1.257427,1.869532,-1.869532,13.060708,-0.314576,0.387470

In [48]:
pwt_csv_grouped = pwt_csv.groupby(by=["countrycode"])

In [49]:
# Make them balanced  
# Group by country code and find the minimum year for each country
min_years_by_country = pwt_csv.groupby('countrycode')['year'].min()

# Decide that 1960 is the latest allowed starting point
# Delete all countries where starting year is above 1960 

# Filter out countries where the starting year is after 1960
countries_before_1960 = min_years_by_country[min_years_by_country <= 1960].index

# Filter the DataFrame to include only countries with starting year before or in 1960
balanced_data = pwt_csv[pwt_csv['countrycode'].isin(countries_before_1960)]

# Filter out all observations before 1960 
balanced_data = balanced_data[balanced_data['year'] > 1959]

# Filtering the data into the 4 groups 
world_bal_data = balanced_data.copy()
oecd_bal_data = balanced_data[balanced_data['countrycode'].isin(oecd_countries)]
imf_advanced_bal_data = balanced_data[balanced_data['countrycode'].isin(imf_advanced_countries)]
imf_emerging_bal_data = balanced_data[balanced_data['countrycode'].isin(imf_emerging_countries)]

### Checking the scope of compromise with balancing

In [50]:
# How many countries are removed 
num_countries_before = len(pwt_csv['countrycode'].unique())
num_countries_after = len(balanced_data['countrycode'].unique())

# Define functions to calculate the number of countries in each group
def num_countries_in_group(group_name, country_list):
    return len(pwt_csv[pwt_csv['countrycode'].isin(country_list)]['countrycode'].unique())

def num_countries_in_group_after_filter(group_name, country_list):
    return len(balanced_data[balanced_data['countrycode'].isin(country_list)]['countrycode'].unique())

# Calculate the number of countries in each group before filtering
num_countries_in_groups_before = {
    "world": num_countries_in_group("world", pwt_csv['countrycode'].unique()),
    "oecd": num_countries_in_group("oecd", oecd_countries),
    "imf_advanced": num_countries_in_group("imf_advanced", imf_advanced_countries),
    "imf_emerging": num_countries_in_group("imf_emerging", imf_emerging_countries)
}

# Calculate the number of countries in each group after filtering
num_countries_in_groups_after = {
    "world": num_countries_in_group_after_filter("world", pwt_csv['countrycode'].unique()),
    "oecd": num_countries_in_group_after_filter("oecd", oecd_countries),
    "imf_advanced": num_countries_in_group_after_filter("imf_advanced", imf_advanced_countries),
    "imf_emerging": num_countries_in_group_after_filter("imf_emerging", imf_emerging_countries)
}

# Calculate the number of countries removed from each group
num_countries_removed_from_groups = {
    group: num_countries_in_groups_before[group] - num_countries_in_groups_after[group]
    for group in num_countries_in_groups_before
}

# Print the results
for group, num_removed in num_countries_removed_from_groups.items():
    print(f"Number of countries removed from {group} group: {num_removed}")

Number of countries removed from world group: 40
Number of countries removed from oecd group: 8
Number of countries removed from imf_advanced group: 8
Number of countries removed from imf_emerging group: 32